### ISSUE TITLE
Process scannet data

### ISSUE THREAD

**Issue by Sekunde** [chrischoy/SpatioTemporalSegmentation-ScanNet#1]
Hi, 
Thanks for sharing this code.

I noticed there is a difference between two repositories in terms of preprocessing scannetv2 data.

> lib/datasets/preprocessing/scannet.py

The other repository seems no CROP_SIZE; What is the CROP_SIZE used in this repository to get the performance in the benchmark?

**Comment by chrischoy** [comment]
They are the same. If you read the preprocessing CROP_SIZE = -1, which means no crop. Both repos use the same data.

**Comment by Sekunde** [comment]
Thanks for quick feedback;
However, if CROP_SIZE =- 1; I can not pass this assert 
https://github.com/chrischoy/SpatioTemporalSegmentation-ScanNet/blob/master/lib/datasets/preprocessing/scannet.py#L72

did I miss something?

**Comment by chrischoy** [comment]
Ah, use the other preprocessing file from the original repo. It seems that I didn't update the preprocessing on this repo.
